# Generated by Django 3.2 on 2023-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('slug', models.CharField(max_length=50, verbose_name='Сокращенное имя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('slug', models.CharField(max_length=50, verbose_name='Сокращенное имя')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
